version: '3'

services:
  app:
    container_name: "hacker-express"
    build: .
    environment:
      - MONGO_CONN_STRING=${MONGO_CONN_STRING}
    ports:
      - "3000:3000"
    command: "npm run prod"