version: '3'

services:
  app:
    container_name: "hacker-express"
    build: .
    environment:
      - MONGO_CONN_STRING=${MONGO_CONN_STRING}
      - PORT="5000"
    ports:
      - "5000:5000"
    command: "npm run prod"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017